name = "hono-boilerplate"
#main = "src/index.ts"
compatibility_date = "2022-04-17"
type = "javascript"

account_id = "a5eabdc2b11aae9bd5af46bd6a88179e"
workers_dev = true

webpack_config = "webpack.config.js"
kv_namespaces = [ ]


[build]
command = "yarn run build"

[build.upload]
format = "service-worker"

[site]
bucket = "./content"
entry-point = "."
