/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as redemtionSol from "./Redemtion.sol";
export type { redemtionSol };
export type { DustBoyNFT } from "./DustBoyNFT";
